# Generated by Django 3.2 on 2024-07-23 11:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_cuties'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuties',
            name='code',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='cuties',
            name='token',
            field=models.UUIDField(default=uuid.UUID('cc247f1e-07b1-471d-ac68-b647be0d82a5')),
        ),
    ]
