# Generated by Django 3.2 on 2024-07-23 11:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_auto_20240723_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuties',
            name='city',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cuties',
            name='token',
            field=models.UUIDField(default=uuid.UUID('86d6a0af-4103-4c19-9eb4-888e19835097')),
        ),
    ]
