# Generated by Django 3.2 on 2024-07-24 12:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_auto_20240723_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('max_temp', models.FloatField()),
                ('min_temp', models.FloatField()),
                ('avg_temp', models.FloatField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('avg_humidity', models.FloatField()),
                ('avg_pressure', models.FloatField()),
                ('avg_visibility', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='cuties',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cuties',
            name='token',
            field=models.UUIDField(default=uuid.UUID('ae97c4d5-44d7-4418-ae6d-115df68e90a9')),
        ),
    ]
