# Generated by Django 3.2 on 2024-07-24 14:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_auto_20240724_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cuties',
            name='token',
            field=models.UUIDField(default=uuid.UUID('072a2ee4-ada5-46bc-83c0-2f33607d74e0')),
        ),
    ]
