# Generated by Django 3.2 on 2024-07-24 14:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0006_auto_20240724_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='cuties',
            name='token',
            field=models.UUIDField(default=uuid.UUID('43fcb97a-b84b-498f-8bff-ac0a4a202a20')),
        ),
    ]
