# Generated by Django 3.2 on 2024-07-24 15:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0007_auto_20240724_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cuties',
            name='token',
            field=models.UUIDField(default=uuid.UUID('252e324f-facf-4864-aab1-fec4ca7dcc4e')),
        ),
    ]
